default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  timeout: 5000

development:
  <<: *default
  database: bank_accounting_development
test:
  <<: *default
  database: bank_accounting_test

production:
  <<: *default
  database: bank_accounting_production
